[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["clean"]

[tasks.all]
dependencies = [
    "format",
    "build",
]

[tasks.run]
command = "cargo"
args = ["run"]

[tasks.release]
command = "cargo"
args = ["build", "--release"]
dependencies = ["clean"]